### ISSUE TITLE
No module named flask.ext.mandrill

### ISSUE THREAD

**Issue by sparkline-annalyn** [volker48/flask-mandrill#3]
I successfully installed the Mandrill in my app but once I called the extension Mandrill I always get this error:

![image](https://cloud.githubusercontent.com/assets/15081968/13743213/79806c2a-ea1b-11e5-9454-879d067429c8.png)

Any help will be much appreciated.

**Comment by volker48** [comment]
Did you try doing import flask_mandrill instead of flask.ext.mandrill? 

1. What version of Flask are you using? 2. What operating system are you using? 
3. Did you install flask mandrill with pip?
4. Are you using a virtual environment?

I'll check the code, but usually import errors usually have something to do with the python path or something else in the code that's importing the library.

Marcus

**Comment by sparkline-annalyn** [comment]
Yes I tried that one also instead of flask.ext.mandrill I change it to flask_mandrill still I got the same error: No module named flask_mandrill.

1. 0.10.1
2. Windows 7
3. Yes, I used this code pip install flask-mandrill
4. Yes

Thanks, I hope I make sense to you. But I will try to figure it out also.

**Comment by volker48** [comment]
Ok strange. I haven't tested it on Windows only Linux and OS X so maybe it's an operating system issue. Can you please paste the output of pip freeze?

Marcus

**Comment by sparkline-annalyn** [comment]
I guess I set it in a wrong path. It's working now on my side. Thanks you! I find hard to set up this kind of code on my app:

try:
    mandrill_client = mandrill.Mandrill('YOUR_API_KEY')
    template_content = [{'content': 'example content', 'name': 'example name'}]
    message = {'attachments': [{'content': 'ZXhhbXBsZSBmaWxl',
                      'name': 'myfile.txt',
                      'type': 'text/plain'}],
     'auto_html': None,
     'auto_text': None,
     'bcc_address': 'message.bcc_address@example.com',
     'from_email': 'message.from_email@example.com',
     'from_name': 'Example Name',
     'global_merge_vars': [{'content': 'merge1 content', 'name': 'merge1'}],
     'google_analytics_campaign': 'message.from_email@example.com',
     'google_analytics_domains': ['example.com'],
     'headers': {'Reply-To': 'message.reply@example.com'},
     'html': '<p>Example HTML content</p>',
     'images': [{'content': 'ZXhhbXBsZSBmaWxl',
                 'name': 'IMAGECID',
                 'type': 'image/png'}],
     'important': False,
     'inline_css': None,
     'merge': True,
     'merge_language': 'mailchimp',
     'merge_vars': [{'rcpt': 'recipient.email@example.com',
                     'vars': [{'content': 'merge2 content', 'name': 'merge2'}]}],
     'metadata': {'website': 'www.example.com'},
     'preserve_recipients': None,
     'recipient_metadata': [{'rcpt': 'recipient.email@example.com',
                             'values': {'user_id': 123456}}],
     'return_path_domain': None,
     'signing_domain': None,
     'subaccount': 'customer-123',
     'subject': 'example subject',
     'tags': ['password-resets'],
     'text': 'Example text content',
     'to': [{'email': 'recipient.email@example.com',
             'name': 'Recipient Name',
             'type': 'to'}],
     'track_clicks': None,
     'track_opens': None,
     'tracking_domain': None,
     'url_strip_qs': None,
     'view_content_link': None}
    result = mandrill_client.messages.send_template(template_name='example template_name', template_content=template_content, message=message, async=False, ip_pool='Main Pool', send_at='example send_at')
    '''
    [{'_id': 'abc123abc123abc123abc123abc123',
      'email': 'recipient.email@example.com',
      'reject_reason': 'hard-bounce',
      'status': 'sent'}]
    '''

except mandrill.Error, e:
    # Mandrill errors are thrown as exceptions
    print 'A mandrill error occurred: %s - %s' % (e.__class__, e)
    # A mandrill error occurred: <class 'mandrill.UnknownSubaccountError'> - No subaccount exists with the id 'customer-123'
    raise
