### ISSUE TITLE
Passing variables to my template

### ISSUE THREAD

**Issue by archienorman11** [volker48/flask-mandrill#6]
Hi, I realise this isn't an issue, but wondered if you could point me in the right direction to adding variables from the flask application to the mandrill template? 
    
    mandrill.send_email(
        from_email='test@test',
        to=[{'email': user.email}],
        subject="TestPassword Reset",
        template_name="password-reset",
        template_content= [
            {
                 "name": user.first_name,
                  "token": token
             }
          ]
    )

**Comment by volker48** [comment]
Sorry, just saw this. I need a little more information to help you if you didn't already find a solution. I assume you are calling `mandrill.send_email` within the view code of one of your routes so you should have all request variables at your disposal. If you are using [Flask-Login the current user](https://flask-login.readthedocs.io/en/latest/#flask_login.current_user) can be accessed with `current_user`.

**Comment by marcelmfs** [comment]
```
template_name='mytemplate',
my_template_mc-edit-varname='value for varname',
```
